# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

CU=/usr/bin/clang
CC=/usr/bin/gcc
AS=/usr/bin/gcc
MM=/usr/bin/gcc
CXX=/usr/bin/gcc
MXX=/usr/bin/gcc

SH=/usr/bin/g++
LD=/usr/bin/g++
AR=/usr/bin/ar

cocpp_CXXFLAGS=-m64 -g -O0 -std=c++2a -Iinclude
cocpp_LDFLAGS=-m64 -lpthread

default:  cocpp

all:  cocpp

.PHONY: default all  cocpp

cocpp: build/linux/x86_64/debug/cocpp
build/linux/x86_64/debug/cocpp: build/.objs/cocpp/linux/x86_64/debug/source/co_default_manager.cpp.o build/.objs/cocpp/linux/x86_64/debug/source/co_default_ctx_factory.cpp.o build/.objs/cocpp/linux/x86_64/debug/source/co_o1_scheduler.cpp.o build/.objs/cocpp/linux/x86_64/debug/source/co_default_env_factory.cpp.o build/.objs/cocpp/linux/x86_64/debug/source/co_default_entry.cpp.o build/.objs/cocpp/linux/x86_64/debug/source/co_ret.cpp.o build/.objs/cocpp/linux/x86_64/debug/source/co_default_stack.cpp.o build/.objs/cocpp/linux/x86_64/debug/source/co_default_env.cpp.o build/.objs/cocpp/linux/x86_64/debug/source/co_default_stack_factory.cpp.o build/.objs/cocpp/linux/x86_64/debug/source/co_env.cpp.o build/.objs/cocpp/linux/x86_64/debug/source/co.cpp.o build/.objs/cocpp/linux/x86_64/debug/source/co_default_ctx.cpp.o build/.objs/cocpp/linux/x86_64/debug/source/co_o1_scheduler_factory.cpp.o build/.objs/cocpp/linux/x86_64/debug/test/test1.cpp.o
	@echo linking.debug cocpp
	@mkdir -p build/linux/x86_64/debug
	@$(LD) -o build/linux/x86_64/debug/cocpp build/.objs/cocpp/linux/x86_64/debug/source/co_default_manager.cpp.o build/.objs/cocpp/linux/x86_64/debug/source/co_default_ctx_factory.cpp.o build/.objs/cocpp/linux/x86_64/debug/source/co_o1_scheduler.cpp.o build/.objs/cocpp/linux/x86_64/debug/source/co_default_env_factory.cpp.o build/.objs/cocpp/linux/x86_64/debug/source/co_default_entry.cpp.o build/.objs/cocpp/linux/x86_64/debug/source/co_ret.cpp.o build/.objs/cocpp/linux/x86_64/debug/source/co_default_stack.cpp.o build/.objs/cocpp/linux/x86_64/debug/source/co_default_env.cpp.o build/.objs/cocpp/linux/x86_64/debug/source/co_default_stack_factory.cpp.o build/.objs/cocpp/linux/x86_64/debug/source/co_env.cpp.o build/.objs/cocpp/linux/x86_64/debug/source/co.cpp.o build/.objs/cocpp/linux/x86_64/debug/source/co_default_ctx.cpp.o build/.objs/cocpp/linux/x86_64/debug/source/co_o1_scheduler_factory.cpp.o build/.objs/cocpp/linux/x86_64/debug/test/test1.cpp.o $(cocpp_LDFLAGS) > build/.build.log 2>&1

build/.objs/cocpp/linux/x86_64/debug/source/co_default_manager.cpp.o: source/co_default_manager.cpp
	@echo compiling.debug source/co_default_manager.cpp
	@mkdir -p build/.objs/cocpp/linux/x86_64/debug/source
	@$(CXX) -c $(cocpp_CXXFLAGS) -o build/.objs/cocpp/linux/x86_64/debug/source/co_default_manager.cpp.o source/co_default_manager.cpp > build/.build.log 2>&1

build/.objs/cocpp/linux/x86_64/debug/source/co_default_ctx_factory.cpp.o: source/co_default_ctx_factory.cpp
	@echo compiling.debug source/co_default_ctx_factory.cpp
	@mkdir -p build/.objs/cocpp/linux/x86_64/debug/source
	@$(CXX) -c $(cocpp_CXXFLAGS) -o build/.objs/cocpp/linux/x86_64/debug/source/co_default_ctx_factory.cpp.o source/co_default_ctx_factory.cpp > build/.build.log 2>&1

build/.objs/cocpp/linux/x86_64/debug/source/co_o1_scheduler.cpp.o: source/co_o1_scheduler.cpp
	@echo compiling.debug source/co_o1_scheduler.cpp
	@mkdir -p build/.objs/cocpp/linux/x86_64/debug/source
	@$(CXX) -c $(cocpp_CXXFLAGS) -o build/.objs/cocpp/linux/x86_64/debug/source/co_o1_scheduler.cpp.o source/co_o1_scheduler.cpp > build/.build.log 2>&1

build/.objs/cocpp/linux/x86_64/debug/source/co_default_env_factory.cpp.o: source/co_default_env_factory.cpp
	@echo compiling.debug source/co_default_env_factory.cpp
	@mkdir -p build/.objs/cocpp/linux/x86_64/debug/source
	@$(CXX) -c $(cocpp_CXXFLAGS) -o build/.objs/cocpp/linux/x86_64/debug/source/co_default_env_factory.cpp.o source/co_default_env_factory.cpp > build/.build.log 2>&1

build/.objs/cocpp/linux/x86_64/debug/source/co_default_entry.cpp.o: source/co_default_entry.cpp
	@echo compiling.debug source/co_default_entry.cpp
	@mkdir -p build/.objs/cocpp/linux/x86_64/debug/source
	@$(CXX) -c $(cocpp_CXXFLAGS) -o build/.objs/cocpp/linux/x86_64/debug/source/co_default_entry.cpp.o source/co_default_entry.cpp > build/.build.log 2>&1

build/.objs/cocpp/linux/x86_64/debug/source/co_ret.cpp.o: source/co_ret.cpp
	@echo compiling.debug source/co_ret.cpp
	@mkdir -p build/.objs/cocpp/linux/x86_64/debug/source
	@$(CXX) -c $(cocpp_CXXFLAGS) -o build/.objs/cocpp/linux/x86_64/debug/source/co_ret.cpp.o source/co_ret.cpp > build/.build.log 2>&1

build/.objs/cocpp/linux/x86_64/debug/source/co_default_stack.cpp.o: source/co_default_stack.cpp
	@echo compiling.debug source/co_default_stack.cpp
	@mkdir -p build/.objs/cocpp/linux/x86_64/debug/source
	@$(CXX) -c $(cocpp_CXXFLAGS) -o build/.objs/cocpp/linux/x86_64/debug/source/co_default_stack.cpp.o source/co_default_stack.cpp > build/.build.log 2>&1

build/.objs/cocpp/linux/x86_64/debug/source/co_default_env.cpp.o: source/co_default_env.cpp
	@echo compiling.debug source/co_default_env.cpp
	@mkdir -p build/.objs/cocpp/linux/x86_64/debug/source
	@$(CXX) -c $(cocpp_CXXFLAGS) -o build/.objs/cocpp/linux/x86_64/debug/source/co_default_env.cpp.o source/co_default_env.cpp > build/.build.log 2>&1

build/.objs/cocpp/linux/x86_64/debug/source/co_default_stack_factory.cpp.o: source/co_default_stack_factory.cpp
	@echo compiling.debug source/co_default_stack_factory.cpp
	@mkdir -p build/.objs/cocpp/linux/x86_64/debug/source
	@$(CXX) -c $(cocpp_CXXFLAGS) -o build/.objs/cocpp/linux/x86_64/debug/source/co_default_stack_factory.cpp.o source/co_default_stack_factory.cpp > build/.build.log 2>&1

build/.objs/cocpp/linux/x86_64/debug/source/co_env.cpp.o: source/co_env.cpp
	@echo compiling.debug source/co_env.cpp
	@mkdir -p build/.objs/cocpp/linux/x86_64/debug/source
	@$(CXX) -c $(cocpp_CXXFLAGS) -o build/.objs/cocpp/linux/x86_64/debug/source/co_env.cpp.o source/co_env.cpp > build/.build.log 2>&1

build/.objs/cocpp/linux/x86_64/debug/source/co.cpp.o: source/co.cpp
	@echo compiling.debug source/co.cpp
	@mkdir -p build/.objs/cocpp/linux/x86_64/debug/source
	@$(CXX) -c $(cocpp_CXXFLAGS) -o build/.objs/cocpp/linux/x86_64/debug/source/co.cpp.o source/co.cpp > build/.build.log 2>&1

build/.objs/cocpp/linux/x86_64/debug/source/co_default_ctx.cpp.o: source/co_default_ctx.cpp
	@echo compiling.debug source/co_default_ctx.cpp
	@mkdir -p build/.objs/cocpp/linux/x86_64/debug/source
	@$(CXX) -c $(cocpp_CXXFLAGS) -o build/.objs/cocpp/linux/x86_64/debug/source/co_default_ctx.cpp.o source/co_default_ctx.cpp > build/.build.log 2>&1

build/.objs/cocpp/linux/x86_64/debug/source/co_o1_scheduler_factory.cpp.o: source/co_o1_scheduler_factory.cpp
	@echo compiling.debug source/co_o1_scheduler_factory.cpp
	@mkdir -p build/.objs/cocpp/linux/x86_64/debug/source
	@$(CXX) -c $(cocpp_CXXFLAGS) -o build/.objs/cocpp/linux/x86_64/debug/source/co_o1_scheduler_factory.cpp.o source/co_o1_scheduler_factory.cpp > build/.build.log 2>&1

build/.objs/cocpp/linux/x86_64/debug/test/test1.cpp.o: test/test1.cpp
	@echo compiling.debug test/test1.cpp
	@mkdir -p build/.objs/cocpp/linux/x86_64/debug/test
	@$(CXX) -c $(cocpp_CXXFLAGS) -o build/.objs/cocpp/linux/x86_64/debug/test/test1.cpp.o test/test1.cpp > build/.build.log 2>&1

clean:  clean_cocpp

clean_cocpp: 
	@rm -rf build/linux/x86_64/debug/cocpp
	@rm -rf build/linux/x86_64/debug/cocpp.sym
	@rm -rf build/.objs/cocpp/linux/x86_64/debug/source/co_default_manager.cpp.o
	@rm -rf build/.objs/cocpp/linux/x86_64/debug/source/co_default_ctx_factory.cpp.o
	@rm -rf build/.objs/cocpp/linux/x86_64/debug/source/co_o1_scheduler.cpp.o
	@rm -rf build/.objs/cocpp/linux/x86_64/debug/source/co_default_env_factory.cpp.o
	@rm -rf build/.objs/cocpp/linux/x86_64/debug/source/co_default_entry.cpp.o
	@rm -rf build/.objs/cocpp/linux/x86_64/debug/source/co_ret.cpp.o
	@rm -rf build/.objs/cocpp/linux/x86_64/debug/source/co_default_stack.cpp.o
	@rm -rf build/.objs/cocpp/linux/x86_64/debug/source/co_default_env.cpp.o
	@rm -rf build/.objs/cocpp/linux/x86_64/debug/source/co_default_stack_factory.cpp.o
	@rm -rf build/.objs/cocpp/linux/x86_64/debug/source/co_env.cpp.o
	@rm -rf build/.objs/cocpp/linux/x86_64/debug/source/co.cpp.o
	@rm -rf build/.objs/cocpp/linux/x86_64/debug/source/co_default_ctx.cpp.o
	@rm -rf build/.objs/cocpp/linux/x86_64/debug/source/co_o1_scheduler_factory.cpp.o
	@rm -rf build/.objs/cocpp/linux/x86_64/debug/test/test1.cpp.o

