FROM alpine:latest
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
RUN apk add curl bash
RUN bash <(curl -fsSL https://xmake.io/shget.text)
RUN chmod 777 -R /root/
ENV PATH /root/.local/bin:$PATH
ENV XMAKE_ROOT y
COPY build.sh /build.sh
ENTRYPOINT ["/build.sh"]